[workspace]
members = [
	"apb",
	"core",
	"cli",
	"migrations",
	"routes",
	"worker",
	"utils/httpsign",
	"utils/mdhtml",
	"utils/uriproxy",
]

[package]
name = "upub-bin"
version = "0.7.2"
edition = "2024"
authors = [ "alemi <me@alemi.dev>" ]
description = "micro social network, federated"
license = "AGPL-3.0"
keywords = ["activitypub", "activitystreams", "json"]
repository = "https://github.com/alemidev/upub"
readme = "README.md"

[[bin]]
name = "upub"
path = "main.rs"

[dependencies]
toml = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.45", features = ["rt-multi-thread", "macros", "signal"] }
sea-orm = { version = "1.1", features = ["sqlx-sqlite", "sqlx-postgres", "runtime-tokio-rustls"] }
futures = "0.3"

upub = { path = "core", version = "0.7" }
upub-cli = { path = "cli", version = "0.3", optional = true }
upub-migrations = { path = "migrations", version = "0.4", optional = true }
upub-routes = { path = "routes", version = "0.5", optional = true }
upub-worker = { path = "worker", version = "0.3", optional = true }

[features]
default = ["serve", "migrate", "cli", "worker"]
serve = ["dep:upub-routes"]
migrate = ["dep:upub-migrations"]
cli = ["dep:upub-cli"]
worker = ["dep:upub-worker"]
web = ["upub-routes?/web"]
web-build-fe = ["upub-routes?/web-build-fe"]
openssl-vendored = ["upub/openssl-vendored", "upub-cli/openssl-vendored", "upub-routes/openssl-vendored"]

# upub: ~38M
# upub-web: ~9M
# [profile.release] # without any tweak

# upub: ~22M
# upub-web.wasm: ~5.8M
[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1

# upub: ~18M
# upub-web.wasm: ~4.1M
[profile.release-tiny]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
