[workspace]
members = [
	"apb",
	"core",
	"cli",
	"migrations",
	"routes",
	"worker",
	"utils/httpsign",
	"utils/mdhtml",
	"utils/uriproxy",
]

[workspace.dependencies]
# core
clap = { version = "4.5", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "2.0"
base64 = "0.22"
hmac = "0.12"
sha2 = "0.10"
sha256 = "1.6" # TODO can we do it with just sha2?
openssl = "0.10" # TODO handle pubkeys with a smaller crate
rand = "0.10"
lazy_static = "1.5"
regex = "1.12"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.20", features = ["v4"] }
paste = "1.0"

# ser/de
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_default =  "0.2"
serde-inline-default = "1.0"
toml = "0.9"
jrd = "0.1"

# async
tokio = "1.49"
async-recursion = "1.1"
async-trait = "0.1"
futures = "0.3"

# http
axum = "0.8"
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "trace", "timeout"] }
reqwest = { version = "0.13", features = ["json"] }

# orm
sea-orm = "1.1"
sea-orm-migration = "1.1"

# wasm
dashmap = "6.1"
cookie = "0.18"
tracing-subscriber-wasm = "0.1"
console_error_panic_hook = "0.1"
leptos = { version = "0.8", features = ["csr", "tracing"] }
leptos_router = { version = "0.8", features = ["tracing"] }
leptos-use = "0.18"
codee = { version = "0.3", features = ["json_serde"] }
tld = "2.36"
web-sys = { version = "=0.3.77", features = ["Screen"] } # this is locked because trunk can't build wasm-bindgen 0.2.108

# upub components
apb = { version = "0.3", path = "apb", features = ["unstructured", "activitypub-fe", "activitypub-counters", "litepub", "did-core"] }
upub = { version = "0.7", path = "core" }
upub-cli = { version = "0.3", path = "cli" }
upub-migrations = { version = "0.4", path = "migrations" }
upub-routes = { version = "0.5", path = "routes" }
upub-worker = { version = "0.3", path = "worker" }
httpsign = { version = "0.1", path = "utils/httpsign", features = ["axum", "query-compat"] }
mdhtml = { version = "0.1", path = "utils/mdhtml" }
uriproxy = { version = "0.1", path = "utils/uriproxy" }
nodeinfo-upub = "0.0.3"

# extras
html5ever = "0.27" # have to lock this because newer versions don't get &mut self anymore
comrak = "0.50"

[workspace.lints]
rust.unsafe_code = "deny"
clippy.unwrap_used = "deny"
clippy.collapsible_if = "allow" # if let() chaining is now allowed, will eventually update all of them

[package]
name = "upub-bin"
version = "0.7.3"
edition = "2024"
authors = [ "alemi <me@alemi.dev>" ]
description = "micro social network, federated"
license = "AGPL-3.0"
keywords = ["activitypub", "activitystreams", "json"]
repository = "https://github.com/alemidev/upub"
readme = "README.md"

[[bin]]
name = "upub"
path = "main.rs"

[dependencies]
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
sea-orm = { workspace = true, features = ["sqlx-sqlite", "sqlx-postgres", "runtime-tokio-rustls"] }

upub.workspace = true
upub-cli = { workspace = true, optional = true }
upub-migrations = { workspace = true, optional = true }
upub-routes = { workspace = true, optional = true }
upub-worker = { workspace = true, optional = true }

[features]
default = ["serve", "migrate", "cli", "worker"]
serve = ["dep:upub-routes"]
migrate = ["dep:upub-migrations"]
cli = ["dep:upub-cli"]
worker = ["dep:upub-worker"]
web = ["upub-routes?/web"]
web-build-fe = ["upub-routes?/web-build-fe"]
openssl-vendored = ["upub/openssl-vendored", "upub-cli/openssl-vendored", "upub-routes/openssl-vendored"]

# upub: ~38M
# upub-web: ~9M
# [profile.release] # without any tweak

# upub: ~22M
# upub-web.wasm: ~5.8M
[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1

# upub: ~18M
# upub-web.wasm: ~4.1M
[profile.release-tiny]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
