[package]
name = "upub-migrations"
version = "0.4.1"
edition = "2024"
authors = [ "alemi <me@alemi.dev>" ]
description = "database migrations for upub"
license = "AGPL-3.0"
repository = "https://github.com/alemidev/upub.git"
readme = "README.md"

[lib]

[dependencies]
sea-orm-migration.workspace = true

[features]
default = []
not-simplified = []

[lints]
workspace = true
