[package]
name = "upub-routes"
version = "0.5.0"
edition = "2024"
authors = [ "alemi <me@alemi.dev>" ]
description = "api route definitions for upub"
license = "AGPL-3.0"
repository = "https://git.alemi.dev/upub.git"
readme = "README.md"

[lib]

[dependencies]
upub.workspace = true
thiserror.workspace = true
rand.workspace = true
sha256.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
jrd.workspace = true
tracing.workspace = true
tokio.workspace = true
reqwest.workspace = true
axum = { workspace = true, features = ["multipart"] }
tower.workspace = true
tower-http.workspace = true
httpsign.workspace = true
sea-orm.workspace = true
nodeinfo-upub.workspace = true
apb = { workspace = true, features = ["orm", "ostatus", "toot", "jsonld"] }
# mastodon
mastodon-async-entities = { version = "1.1.0", optional = true }

[features]
default = ["activitypub"]
activitypub = []
mastodon = ["dep:mastodon-async-entities"]
web = []
web-redirect = []
activitypub-redirect = []
openssl-vendored = ["httpsign/openssl-vendored"]
web-build-fe = []

[lints]
workspace = true
