[package]
name = "upub-routes"
version = "0.5.0"
edition = "2024"
authors = [ "alemi <me@alemi.dev>" ]
description = "api route definitions for upub"
license = "AGPL-3.0"
repository = "https://git.alemi.dev/upub.git"
readme = "README.md"

[lib]

[dependencies]
thiserror = "2.0"
rand = "0.9"
sha256 = "1.6" # TODO ughhh
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
upub = { path = "../core/", version = "0.7" }
jrd = "0.1"
tracing = "0.1"
tokio = "1.45"
reqwest = { version = "0.12", features = ["json"] }
axum = { version = "0.8", features = ["multipart"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "trace", "timeout"] }
httpsign = { path = "../utils/httpsign/", version = "0.1", features = ["axum"] }
apb = { path = "../apb/", version = "0.3", features = ["unstructured", "orm", "activitypub-fe", "activitypub-counters", "litepub", "ostatus", "toot", "jsonld"] }
sea-orm = "1.1"
nodeinfo-upub = "0.0.3"
# mastodon
mastodon-async-entities = { version = "1.1.0", optional = true }
time = { version = "0.3", features = ["serde"], optional = true }
# frontend
leptos = { version = "0.8", optional = true }
leptos_router = { version = "0.8", optional = true }
leptos_axum = { version = "0.8", optional = true }
leptos_meta = { version = "0.8", optional = true }

[features]
default = ["activitypub"]
activitypub = []
mastodon = ["dep:mastodon-async-entities"]
web = [
	"dep:leptos",
	"dep:leptos_router",
	"dep:leptos_axum",
	"dep:leptos_meta"
]
web-redirect = []
activitypub-redirect = []
openssl-vendored = ["httpsign/openssl-vendored"]
