[package]
name = "upub-cli"
version = "0.3.2"
edition = "2024"
authors = [ "alemi <me@alemi.dev>" ]
description = "cli maintenance tasks for upub"
license = "AGPL-3.0"
repository = "https://git.alemi.dev/upub.git"
readme = "README.md"

[lib]

[dependencies]
apb.workspace = true
upub.workspace = true
tracing.workspace = true
serde_json.workspace = true
sha256.workspace = true
uuid.workspace = true
chrono.workspace = true
openssl.workspace = true
clap.workspace = true
sea-orm.workspace = true
futures.workspace = true
reqwest.workspace = true

[features]
default = []
openssl-vendored = ["openssl/vendored"]

[lints]
workspace = true
