[package]
name = "upub"
version = "0.7.3"
edition = "2024"
authors = [ "alemi <me@alemi.dev>" ]
description = "core inner workings of upub"
license = "AGPL-3.0"
repository = "https://github.com/alemidev/upub"
readme = "README.md"

[lib]

[dependencies]
tracing.workspace = true
thiserror.workspace = true
async-recursion.workspace = true
async-trait.workspace = true
sha256.workspace = true
sha2.workspace = true
hmac.workspace = true
openssl.workspace = true
base64.workspace = true
chrono.workspace = true
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_default.workspace = true
serde-inline-default.workspace = true
toml.workspace = true
uriproxy.workspace = true
httpsign.workspace = true
mdhtml.workspace = true
jrd.workspace = true
sea-orm = { workspace = true, features = ["macros"] }
reqwest.workspace = true
nodeinfo-upub.workspace = true
apb = { workspace = true, features = ["orm", "activitypub-miscellaneous-terms", "ostatus", "toot", "jsonld"] }

[features]
default = []
openssl-vendored = ["openssl/vendored", "httpsign/openssl-vendored"]

[lints]
workspace = true
