[package]
name = "upub-migrations"
version = "0.4.0"
edition = "2021"
authors = [ "alemi <me@alemi.dev>" ]
description = "database migrations for upub"
license = "AGPL-3.0"
repository = "https://git.alemi.dev/upub.git"
readme = "README.md"

[lib]

[dependencies]
sea-orm-migration = "1.0"
