[package]
name = "upub-worker"
version = "0.3.1"
edition = "2024"
authors = [ "alemi <me@alemi.dev>" ]
description = "upub background activity processing and dispatching workers"
license = "AGPL-3.0"
repository = "https://git.alemi.dev/upub.git"
readme = "README.md"

[lib]

[dependencies]
thiserror.workspace = true
tracing.workspace = true
serde_json.workspace = true
sea-orm.workspace = true
regex.workspace = true
chrono.workspace = true
reqwest.workspace = true
tokio = { workspace = true, features = ["time", "macros"] }

mdhtml.workspace = true
upub.workspace = true
apb = { workspace = true, features = ["orm", "ostatus", "toot"] }

[lints]
workspace = true
