on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
         curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-install.sh
         chmod +x rustup-install.sh
         ./rustup-install.sh -y
      - run: cargo test

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
         curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-install.sh
         chmod +x rustup-install.sh
         ./rustup-install.sh -y
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install --locked trunk
      - run: trunk build --release
        working-directory: web/
      - run: cargo build --release --features=web
      - uses: actions/upload-artifact@v4
        with:
          path: target/release/upub
