on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
         curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-install.sh
         chmod +x rustup-install.sh
         ./rustup-install.sh -y
      - run: $HOME/.cargo/bin/rustup target add wasm32-unknown-unknown
      - run: |
         curl --proto '=https' --tlsv1.2 -sSfL https://github.com/trunk-rs/trunk/releases/download/v0.21.7/trunk-x86_64-unknown-linux-gnu.tar.gz > $HOME/.cargo/bin/trunk.tar.gz
         tar --directory $HOME/.cargo/bin/ -xf $HOME/.cargo/bin/trunk.tar.gz
      - uses: actions/checkout@v4
      - run: alias cargo=$HOME/.cargo/bin/cargo; $HOME/.cargo/bin/trunk build --release
        working-directory: web/
      - run: $HOME/.cargo/bin/cargo build --release --features=web
      - uses: actions/upload-artifact@v4
        with:
          path: target/release/upub
