name: Test

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install trunk
      - run: cargo install wasm-bindgen-cli # github may use a cached version
      - uses: actions/checkout@v4
      - run: trunk build --release
        working-directory: web/
      - run: cargo build --features=web
      - run: cargo test --features=web
