name: Test

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install trunk
      - run: cargo install -f wasm-bindgen-cli --version 0.2.108 # github CI issue? builds locally...
      - uses: actions/checkout@v4
      - run: trunk build --release
        working-directory: web/
      - run: cargo build --features=web
      - run: cargo test --features=web
