[package]
name = "upub-web"
version = "0.7.3"
edition = "2024"
authors = [ "alemi <me@alemi.dev>" ]
description = "web frontend for upub"
license = "AGPL-3.0"
keywords = ["activitypub", "upub", "json", "web", "wasm"]
repository = "https://github.com/alemidev/upub"
readme = "README.md"

[dependencies]
tracing.workspace = true
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_default.workspace = true
serde-inline-default.workspace = true
lazy_static.workspace = true
cookie.workspace = true
tracing-subscriber.workspace = true
tracing-subscriber-wasm.workspace = true
console_error_panic_hook.workspace = true
dashmap.workspace = true
leptos.workspace = true
leptos_router.workspace = true
leptos-use.workspace = true
codee.workspace = true
reqwest.workspace = true
apb.workspace = true
uriproxy.workspace = true
mdhtml.workspace = true
futures.workspace = true
chrono.workspace = true
jrd.workspace = true
tld.workspace = true
web-sys.workspace = true
regex.workspace = true

[package.metadata.trunk.build]
public_url = "/web/assets/"
filehash = false
#offline = true # if you're looking in here, you may want to uncomment this and download wasm-bindgen-cli yourself

[lints]
workspace = true
