# need to make it a workspace so it has a separate
# target/ dir and it builds separately from main upub
[workspace]

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-subscriber-wasm = "0.1"
base64 = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_default =  "0.2"
serde-inline-default = "1.0"
lazy_static = "1.5"
dashmap = "6.1"
cookie = "0.18"
console_error_panic_hook = "0.1"
leptos = { version = "0.8", features = ["csr", "tracing"] }
leptos_router = { version = "0.8", features = ["tracing"] }
leptos-use = "0.18"
codee = { version = "0.3", features = ["json_serde"] }
tld = "2.36"
web-sys = { version = "=0.3.77", features = ["Screen"] } # this is locked because trunk can't build wasm-bindgen 0.2.108
reqwest = { version = "0.13", features = ["json"] }
apb = { version = "0.3", path = "../apb", features = ["unstructured", "activitypub-fe", "activitypub-counters", "litepub", "did-core"] }
uriproxy = { version = "0.1", path = "../utils/uriproxy" }
mdhtml = { version = "0.1", path = "../utils/mdhtml" }
futures = "0.3"
chrono = { version = "0.4", features = ["serde"] }
regex = "1.12"
jrd = "0.1"

[workspace.lints]
rust.unsafe_code = "deny"
clippy.unwrap_used = "deny"
clippy.collapsible_if = "allow" # if let() chaining is now allowed, will eventually update all of them

[package]
name = "upub-web"
version = "0.7.3"
edition = "2024"
authors = [ "alemi <me@alemi.dev>" ]
description = "web frontend for upub"
license = "AGPL-3.0"
keywords = ["activitypub", "upub", "json", "web", "wasm"]
repository = "https://github.com/alemidev/upub"
readme = "README.md"

[dependencies]
tracing.workspace = true
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_default.workspace = true
serde-inline-default.workspace = true
lazy_static.workspace = true
cookie.workspace = true
tracing-subscriber.workspace = true
tracing-subscriber-wasm.workspace = true
console_error_panic_hook.workspace = true
dashmap.workspace = true
leptos.workspace = true
leptos_router.workspace = true
leptos-use.workspace = true
codee.workspace = true
reqwest.workspace = true
apb.workspace = true
uriproxy.workspace = true
mdhtml.workspace = true
futures.workspace = true
chrono.workspace = true
jrd.workspace = true
tld.workspace = true
web-sys.workspace = true
regex.workspace = true

[package.metadata.trunk.build]
public_url = "/web/assets/"
filehash = false
#offline = true # if you're looking in here, you may want to uncomment this and download wasm-bindgen-cli yourself

[lints]
workspace = true
